Freemius SDK Upgrade - WP feedback incorporate
glowlogix/wp-frontend-profile pull request #95
Opened 2022-05-11 14:00 UTC by abuzar347

2022-05-12 11:20 UTC, afifa-glowlogix requested changes

2022-05-12 21:36 UTC, musamamasood commented on CHANGELOG.md
>  ## [Unreleased]
Still there and linked to the master branch and the latest release.

2022-05-13 07:13 UTC, afifa-glowlogix requested changes

2022-05-13 07:13 UTC, afifa-glowlogix commented on CHANGELOG.md
> +## [1.2.6] - 2022-02-12
@abuzar347 release date for 1.2.6 is 2022-04-22
Also, match the format of the last two releases to the order releases and update fixes as well.

2022-05-13 12:31 UTC, afifa-glowlogix commented
@abuzar347  release date for 1.2.6 version is 04/22/2022, not 5th April.

2022-05-13 12:32 UTC, afifa-glowlogix requested changes

2022-05-13 12:32 UTC, afifa-glowlogix commented on CHANGELOG.md
> +## [1.2.6] - 2022-04-05
@abuzar347  release date for 1.2.6 version is 04/22/2022, not 5th April.

2022-05-13 12:51 UTC, afifa-glowlogix approved these changes

2022-05-13 13:33 UTC, merged