Tested with WordPress 6.1
glowlogix/wp-frontend-profile pull request #99
Opened 2022-11-02 18:25 UTC by hasnain37

2022-11-02 21:47 UTC, musamamasood commented
@hasnain37 @afifa-glowlogix please review changes as it revert back to old changes of array syntax.

2022-11-02 21:48 UTC, musamamasood commented
Also, resolve conflicts as well.

2022-11-02 21:56 UTC, musamamasood commented
https://github.com/glowlogix/wp-frontend-profile/issues/100

2022-11-03 07:14 UTC, afifa-glowlogix commented
@hasnain37 kindly run the code through csfixer once.

2022-11-08 07:27 UTC, afifa-glowlogix commented
@hasnain37 please resolve conflicts.

2023-01-04 20:15 UTC, musamamasood commented on inc/class-wpfep-profile.php
> +            return apply_filters('wpfep_profile_url', $url);
@hasnain37 why `$page_id` exclude from `filter`?

2023-01-04 20:16 UTC, musamamasood requested changes
Please review comments

2023-01-05 15:00 UTC, musamamasood approved these changes

2023-01-05 15:01 UTC, merged